import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/public/globals.css";
import { TRPCProvider } from "@/trpc/client";
import { HydrateClient } from "@/trpc/server";
import { AuthProvider } from "@/lib/provider";
import { ToastProvider } from "@/components/ui/toast";
import { getServerAuthSession } from "@/server/auth";
import { redirect } from "next/navigation";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function DashBoardLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

    const session = await getServerAuthSession();

    if (!session) {
        redirect("/");
    }
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark:text-text-dark`} suppressHydrationWarning={true}>
                <ToastProvider>
                    <TRPCProvider>
                        <HydrateClient>
                            <AuthProvider>
                                <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center mx-auto max-w-7xl min-h-screen p-8 pb-20 gap-16 sm:p-20 overflow-hidden">
                                    {children}
                                    <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
                                        <span className="text-sm text-gray-500">© 2025 Jose Gale</span>
                                    </footer>
                                </div>

                            </AuthProvider>
                        </HydrateClient>
                    </TRPCProvider>
                </ToastProvider>
            </body>
        </html>
    );
}
